version: "3"
services:
  mongodb:
    image: mongo
    container_name: pos-mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: pos-redis
    ports:
      - "6379:6379"